### ISSUE TITLE
"Unexpected CF stack status" while creating a network stack upon bootstrap

### ISSUE THREAD

**Issue by chitsaou** [degica/barcelona#376]
Hi there,

I am trying out barcelona by following [getting_started.md](https://github.com/degica/barcelona/blob/master/docs/getting_started.md), and got this error message:

```
Creating Network Stack../app/lib/tasks/bootstrap.rake:12:in `wait_cf_stack': Unexpected CF stack status (RuntimeError)
	from /app/lib/tasks/bootstrap.rake:35:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
	from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
	from /usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
	from bin/bootstrap:63:in `execute'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from bin/bootstrap:69:in `<main>'
```

My environment is:

* ap-northeast-1
* No ACM Certificate provided
* While running  bin/bootstrap, I provided an AWS user with:
  * Pragmatic access only (access key)
  * Full access:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

The docker image I used is:

     quay.io/degica/barcelona                                     latest              7d5a56bd3e87

Am I missing anything? Or should I create a certificate anyways?

Thanks!

**Comment by k2nr** [comment]
It seems the CloudFormation stack failed to create. Can you go to the AWS web console -> CloudFormation and give me the failure message?

**Comment by chitsaou** [comment]
Okay I found it.

	14:43:35 UTC+0900	CREATE_FAILED	AWS::EC2::InternetGateway	InternetGateway	The maximum number of internet gateways has been reached.

I'll adjust my internet gateways and try again.

Thanks for your help anyways!
