### ISSUE TITLE
Add SSL policy option to endpoint

### ISSUE THREAD

**Issue by k2nr** [degica/barcelona#382]
Currently there's no way to change ALB HTTPS listener security policy.
http://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html

**Comment by k2nr** [comment]
and I want to change the default to `ELBSecurityPolicy-TLS-1-2-2017-01`. I'm wondering if we should abstract the actual AWS's policies as follows

- `modern` -> `ELBSecurityPolicy-TLS-1-2-2017-01`
- `intermidate` -> `ELBSecurityPolicy-2016-08`

I don't think we need to provide other policies, and If we use this higher level abstraction, it's easy to update all existing endpoints to a newer version. For example, assume that there was a newer version `2018-01` released, Barcelona could update all modern load balancers to the new version `2018-01`

**Comment by k2nr** [comment]
My definition here is that `modern` is a policy that supports TLS1.2 and higher, and `intermediate` is a policy that support TLS1.0 or higher. This definition will be changed in the future when the TLS versions are deprecated (considered as insecure) but for now this definition is enough

**Comment by k2nr** [comment]
@essa what do you think about this? there are basically 2 ways; one is providing `modern` / `intermediate` (policies defined by Barcelona which will be translated to AWS's policy) and the other is providing AWS policies such as `ELBSecurityPolicy-2016-08` to Barcelona users.

The main difference is that if we provide Barcelona-defined policies (`modern` and `intermediate`) it is Barcelona's responsibility to keep HTTPS listeners secure, while in the other way, it is Barcelona users' responsibility to keep listeners security

**Comment by essa** [comment]
`modern` is a good option for new users of Barcelona.

But we must warn that, if you use `modern`, upgrading Barcelona means cutting users of deprecated browsers when the policy for `modern` changes.

So I think other option should be something like`default` which we guarantee that the policy for this option will not change forever and provide a way in which users can change the policy when they like to do.

**Comment by k2nr** [comment]
`intermediate` (or `default`? naming is a different discussion but it is important that this policy is default if policy is not specified) policy will change in the future when TLS1.0 is deprecated. But my idea is that `intermediate` policy always support all TLS versions which **is not considered as insecure**
In this sense, we can the actual ALB policy of `intermediate` when it's necessary

**Comment by k2nr** [comment]
Thanks for your comment! I'll implement this

**Comment by k2nr** [comment]
forgot to mention that, at first I was thinking to change the default to `modern` but on sencond thought I decided to not change the default. Now I think it is a good practice to use the same default policy of AWS ALB

**Comment by k2nr** [comment]
FYI, my naming of `modern` and `intermediate` is from https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by essa** [comment]
The term `default` was not clear. Please forget about it.
I don't mind about default. Whether it fits my case or not, I can check it before the service in.

My concern is timing of the deprecation of browsers. Some sites must accept old browsers even if it is not considered as secure.

For example, Basecamp2 accepts DRM activation requests from a license library embedded in application softwares.

What I want is a way to upgrade Barcelona freezing the security policy for existing services even if it is not considered as secure.

**Comment by k2nr** [comment]
I see, that's a good point. Then my idea is to add `old` when deprecation of TLS 1.0 happens:
As an initial step, we just add `modern` and `intermediate` because I don't think we need to support the weakest policy `ELBSecurityPolicy-TLS-1-0-2015-04`. In the future, when we need to change the actual policy of `intermediate` to a securer policy, we add `old` policy that points to the previous ALB policy of `intermediate`

**Comment by k2nr** [comment]
As same as other Barcelona features, I want to make Barcelona keep resources up-to-date and secure on behalf of users. So I don't want to provide a feature to "freeze" the policy. Instead, we will provide insecure option `old` if necessary and users need to explicitly use the `old` policy which understanding that they're making it insecure
