### ISSUE TITLE
Vault as an authentication/authorization backend

### ISSUE THREAD

**Issue by k2nr** [degica/barcelona#401]
I was thinking about fine-grained authorization control https://github.com/degica/barcelona/issues/134 I came up with many ideas but all of them are not easy to implement. Authentication is relatively easy but authorization is always hard.

Instead of implementing access control inside Barcelona, now I'm thinking that it is easier and better to integrate HashiCorp's Vault and use it as a trusted external authorization service.

1. Every time user make a request to Barcelona, the request include Vault token
2. Barcelona calls Vault's `sys/capabilities-self` API with a path `secret/Barcelona/{{prefix}}/{{API path}}`
  1. `sys/capabilities-self` returns capablities on a given path for the token. For example, capabilities look like `["create", "read"]`
  2. Vault has built-in capabilities `create`, `update`, `read`, `delete`. In Barcelona, those capabilities are mapped to corresponding HTTP methods (e.g. `create` -> `POST`)
3. If the given token has a right permission for the API path and HTTP method, Barcelona allows executing the requested API

With this way Barcelona just don't need to care about authentication and authorization. Vault handles everything

## Example

Assume that a Vault token has the following capabilities

```
path "secret/Barcelona/prefix/v1/heritages/my-app*" {
  capabilities = ["read"]
}
```

users with this token can call get general information about `my-app`, can get environment variables of `my-app`, but cannot update/delete environment variables, cannot deploy, cannot do `bcn run` which calls `POST /v1/heritages/my-app/oneoffs`. And of course, this token do not have any permission on district API.

**Comment by essa** [comment]
Seems to be a good idea! 👍 
Vault token can be short lifetime, so it will be far safer.

Can you consider a case of two Barcelona instances sharing one Vault server?
It may be an edge case but it will be needed by us if our Mastodon servers grow.

For example, if I am the super admin for Mastodon but have limited access to our main Barcelona API and I use same Vault token for both Barcelona instances, one should accept all request and the other should reject same of them.

**Comment by k2nr** [comment]
Thanks, nice catch. Each Barcelona service need to have its own unique ID then. I'll think about it

**Comment by k2nr** [comment]
The write request would be `/Barcelona/{{Barcelona unique ID}}/{{API Path}}/{{HTTP method}}`

**Comment by k2nr** [comment]
I've never heard of this idea (Vault generic secret backend as an external service authorization backend). Maybe because that's a new good idea or maybe it's just a bad idea...

**Comment by k2nr** [comment]
I found `sys/capabilities-self` API so we don't need to actually write to generic secret backend. Updated the description.
