### ISSUE TITLE
Autoscaling groups should not create their own log groups

### ISSUE THREAD

**Issue by olingern** [degica/barcelona#465]
Not sure why this is, but the log groups are mostly empty and not helpful in understanding what log groups they're actually for:

![image](https://user-images.githubusercontent.com/1470297/42678578-465f6baa-86ba-11e8-8f2d-a30271f7a639.png)

**Comment by k2nr** [comment]
that's because I created & deleted many districts for dev & test purpose. normally there is only one log group for ASG draining function
