### ISSUE TITLE
Update nodejs lambda runtime to 10.x

### ISSUE THREAD

**Issue by k2nr** [degica/barcelona#534]
it seems CloudFormation have finally supported nodejs 10.x https://forums.aws.amazon.com/thread.jspa?messageID=908801

**Comment by k2nr** [comment]
@essa can you work on this when you have time?

**Comment by essa** [comment]
Sure

**Comment by k2nr** [comment]
@essa ping. I think all functions are not updatable now

**Comment by essa** [comment]
Sorry, I will do it right now.
