### ISSUE TITLE
Cannot make an endpoint with the same name of a recently deleted endpoint

### ISSUE THREAD

**Issue by davidsiaw** [degica/barcelona#550]
# Context

If you create an endpoint, delete it and recreate one with the same name shortly after, you get an `internal_server_error`

# How to test
1. `bcn endpoint create --district default poky`
2. `bcn endpoint delete --district default poky`
3. `bcn endpoint create --district default poky`
4. Observe that it returns `internal_server_error`

**Comment by Yuuki77** [comment]
Hmm could not reproduce the issue
close it
